POST https://reqres.in/api/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Idempotency-Key: aaaaa

{
    "name": "morpheus",
    "job": "leader",
    "array": ["a", "b", "c"],
    "object_ugly_closing": {
      "some_key": "some_value"
}
}
