# Use command :RestSelectEnv ./tests/swappable_env/.env.json
# to select the env file for this request
POST https://jsonplaceholder.typicode.com/posts
Content-type: application/json

{
    "title": "{{TITLE}}",
    "body": "{{BODY}}",
    "userId": 1
}
