@token = YOUR_GITHUB_OAUTH_TOKEN

### GraphQL request (without json variables)
GRAPHQL https://api.github.com/graphql
Authorization: token {{token}}

query {
    repository(name: "NativeVim", owner: "boltlessengineer") {
        name
            fullName: nameWithOwner
            description
            diskUsage
            forkCount
            stargazers(first: 5) {
                totalCount
                nodes {
                    login
                    name
                }
            }
        watchers {
            totalCount
        }
    }
}

### GraphQL request (with json variables)
GRAPHQL https://api.github.com/graphql
Authorization: token {{token}}

query ($name: String!, $owner: String!) {
    repository(name: $name, owner: $owner) {
        name
            fullName: nameWithOwner
            description
            diskUsage
            forkCount
            stargazers(first: 5) {
                totalCount
                nodes {
                    login
                    name
                }
            }
        watchers {
            totalCount
        }
    }
}

{
    "name": "NativeVim",
    "owner": "boltlessengineer"
}
